// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sportify.Data;

#nullable disable

namespace Sportify.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260312221002_AddProfilResmiYolu")]
    partial class AddProfilResmiYolu
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sportify.Models.EpostaOnay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsOnaylandi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("OnayKodu")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.HasKey("Id");

                    b.ToTable("EpostaOnaylar");
                });

            modelBuilder.Entity("Sportify.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmailOnayKodu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEmailOnayli")
                        .HasColumnType("bit");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProfilResmiYolu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SifreSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("Sportify.Models.Lig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bayrak")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sezon")
                        .HasColumnType("int");

                    b.Property<string>("Ulke")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ligler");
                });

            modelBuilder.Entity("Sportify.Models.Mac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Dakika")
                        .HasColumnType("int");

                    b.Property<string>("Deplasman")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeplasmanLogo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DeplasmanSkor")
                        .HasColumnType("int");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EvSahibi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EvSahibiLogo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EvSahibiSkor")
                        .HasColumnType("int");

                    b.Property<string>("LigAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LigLogo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Maclar");
                });

            modelBuilder.Entity("Sportify.Models.Oyuncu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Foto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mevki")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TakimAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TakimLogo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uyruk")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Yas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Oyuncular");
                });

            modelBuilder.Entity("Sportify.Models.PuanDurumu", b =>
                {
                    b.Property<int>("TakimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TakimId"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AtilanGol")
                        .HasColumnType("int");

                    b.Property<int>("Beraberlik")
                        .HasColumnType("int");

                    b.Property<string>("Form")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Galibiyet")
                        .HasColumnType("int");

                    b.Property<int>("GolFarki")
                        .HasColumnType("int");

                    b.Property<int?>("LigId")
                        .HasColumnType("int");

                    b.Property<int>("Maglubiyet")
                        .HasColumnType("int");

                    b.Property<int>("Oynanan")
                        .HasColumnType("int");

                    b.Property<int>("Puan")
                        .HasColumnType("int");

                    b.Property<int>("Sira")
                        .HasColumnType("int");

                    b.Property<string>("TakimAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TakimLogo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YenilenGol")
                        .HasColumnType("int");

                    b.HasKey("TakimId");

                    b.HasIndex("LigId");

                    b.ToTable("PuanDurumlari");
                });

            modelBuilder.Entity("Sportify.Models.Takim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KurulusYili")
                        .HasColumnType("int");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stadyum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ulke")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Takimlar");
                });

            modelBuilder.Entity("Sportify.Models.Oyuncu", b =>
                {
                    b.OwnsOne("Sportify.Models.OyuncuIstatistikleri", "Istatistikler", b1 =>
                        {
                            b1.Property<int>("OyuncuId")
                                .HasColumnType("int");

                            b1.Property<int>("Asistler")
                                .HasColumnType("int");

                            b1.Property<int>("Goller")
                                .HasColumnType("int");

                            b1.Property<int>("IsabetliSutlar")
                                .HasColumnType("int");

                            b1.Property<int>("KirmiziKartlar")
                                .HasColumnType("int");

                            b1.Property<int>("MacSayisi")
                                .HasColumnType("int");

                            b1.Property<int>("OynananDakika")
                                .HasColumnType("int");

                            b1.Property<double>("PasIsabeti")
                                .HasColumnType("float");

                            b1.Property<int>("Paslar")
                                .HasColumnType("int");

                            b1.Property<double>("Reyting")
                                .HasColumnType("float");

                            b1.Property<int>("SariKartlar")
                                .HasColumnType("int");

                            b1.Property<int>("Sutlar")
                                .HasColumnType("int");

                            b1.HasKey("OyuncuId");

                            b1.ToTable("Oyuncular");

                            b1.WithOwner()
                                .HasForeignKey("OyuncuId");
                        });

                    b.Navigation("Istatistikler");
                });

            modelBuilder.Entity("Sportify.Models.PuanDurumu", b =>
                {
                    b.HasOne("Sportify.Models.Lig", null)
                        .WithMany("PuanDurumlari")
                        .HasForeignKey("LigId");
                });

            modelBuilder.Entity("Sportify.Models.Takim", b =>
                {
                    b.OwnsOne("Sportify.Models.TakimIstatistikleri", "Istatistikler", b1 =>
                        {
                            b1.Property<int>("TakimId")
                                .HasColumnType("int");

                            b1.Property<int>("AtilanGol")
                                .HasColumnType("int");

                            b1.Property<int>("Beraberlik")
                                .HasColumnType("int");

                            b1.Property<int>("Galibiyet")
                                .HasColumnType("int");

                            b1.Property<int>("Maglubiyet")
                                .HasColumnType("int");

                            b1.Property<int>("Oynanan")
                                .HasColumnType("int");

                            b1.Property<int>("YenilenGol")
                                .HasColumnType("int");

                            b1.HasKey("TakimId");

                            b1.ToTable("Takimlar");

                            b1.WithOwner()
                                .HasForeignKey("TakimId");
                        });

                    b.Navigation("Istatistikler");
                });

            modelBuilder.Entity("Sportify.Models.Lig", b =>
                {
                    b.Navigation("PuanDurumlari");
                });
#pragma warning restore 612, 618
        }
    }
}
